name: Update opening times from Google
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download latest current opening hours
      run: |-
        curl "${{ secrets.PLACE_API_URL }}" | jq . > _data/current_opening_hours.json
    - name: Commit and push changes (if different)
      run: |-
        git diff
        git config user.name "GitHub Actions: Update opening hours"
        git config user.email "---"
        git diff --quiet || (git add -A && git commit -m "chore: updated opening times from automated action")
        git push
