name: Update opening hours from Google
on:
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download latest current opening hours
      run: |-
        curl --fail --output '_data/current_opening_hours.json' --location 'https://places.googleapis.com/v1/places/${{ vars.PLACE_ID }}' \
        --header 'X-Goog-Api-Key: ${{ secrets.PLACES_API_KEY }}' \
        --header 'X-Goog-FieldMask: currentOpeningHours' \
        --header 'Content-Type: application/json' \
        --header 'Accept: application/json'
    - name: Parse downloaded JSON to test if valid
      run: |-
        cat _data/current_opening_hours.json | jq type 1>/dev/null
    - name: Commit and push changes (if different)
      run: |-
        git diff
        git config user.name "GitHub Actions: Update opening hours"
        git config user.email "---"
        git diff --quiet _data/current_opening_hours.json || (git add _data/current_opening_hours.json && git commit -m "chore: updated opening times from automated action")
        git push
